/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ADecFunctionListDecFunction extends PListDecFunction
{
    private PDecFunction _decFunction_;
    private PListDecFunction _listDecFunction_;

    public ADecFunctionListDecFunction()
    {
        // Constructor
    }

    public ADecFunctionListDecFunction(
        @SuppressWarnings("hiding") PDecFunction _decFunction_,
        @SuppressWarnings("hiding") PListDecFunction _listDecFunction_)
    {
        // Constructor
        setDecFunction(_decFunction_);

        setListDecFunction(_listDecFunction_);

    }

    @Override
    public Object clone()
    {
        return new ADecFunctionListDecFunction(
            cloneNode(this._decFunction_),
            cloneNode(this._listDecFunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFunctionListDecFunction(this);
    }

    public PDecFunction getDecFunction()
    {
        return this._decFunction_;
    }

    public void setDecFunction(PDecFunction node)
    {
        if(this._decFunction_ != null)
        {
            this._decFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFunction_ = node;
    }

    public PListDecFunction getListDecFunction()
    {
        return this._listDecFunction_;
    }

    public void setListDecFunction(PListDecFunction node)
    {
        if(this._listDecFunction_ != null)
        {
            this._listDecFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listDecFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decFunction_)
            + toString(this._listDecFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decFunction_ == child)
        {
            this._decFunction_ = null;
            return;
        }

        if(this._listDecFunction_ == child)
        {
            this._listDecFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decFunction_ == oldChild)
        {
            setDecFunction((PDecFunction) newChild);
            return;
        }

        if(this._listDecFunction_ == oldChild)
        {
            setListDecFunction((PListDecFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
