/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstReturnInstruction extends PInstruction
{
    private PInstReturn _instReturn_;

    public AInstReturnInstruction()
    {
        // Constructor
    }

    public AInstReturnInstruction(
        @SuppressWarnings("hiding") PInstReturn _instReturn_)
    {
        // Constructor
        setInstReturn(_instReturn_);

    }

    @Override
    public Object clone()
    {
        return new AInstReturnInstruction(
            cloneNode(this._instReturn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstReturnInstruction(this);
    }

    public PInstReturn getInstReturn()
    {
        return this._instReturn_;
    }

    public void setInstReturn(PInstReturn node)
    {
        if(this._instReturn_ != null)
        {
            this._instReturn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instReturn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instReturn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instReturn_ == child)
        {
            this._instReturn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instReturn_ == oldChild)
        {
            setInstReturn((PInstReturn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
