/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstCallFunctionInstruction extends PInstruction
{
    private PInstCallFunction _instCallFunction_;

    public AInstCallFunctionInstruction()
    {
        // Constructor
    }

    public AInstCallFunctionInstruction(
        @SuppressWarnings("hiding") PInstCallFunction _instCallFunction_)
    {
        // Constructor
        setInstCallFunction(_instCallFunction_);

    }

    @Override
    public Object clone()
    {
        return new AInstCallFunctionInstruction(
            cloneNode(this._instCallFunction_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstCallFunctionInstruction(this);
    }

    public PInstCallFunction getInstCallFunction()
    {
        return this._instCallFunction_;
    }

    public void setInstCallFunction(PInstCallFunction node)
    {
        if(this._instCallFunction_ != null)
        {
            this._instCallFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instCallFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instCallFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instCallFunction_ == child)
        {
            this._instCallFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instCallFunction_ == oldChild)
        {
            setInstCallFunction((PInstCallFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
