/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstructionListListInst extends PListInst
{
    private PInstruction _instruction_;
    private PListInst _listInst_;

    public AInstructionListListInst()
    {
        // Constructor
    }

    public AInstructionListListInst(
        @SuppressWarnings("hiding") PInstruction _instruction_,
        @SuppressWarnings("hiding") PListInst _listInst_)
    {
        // Constructor
        setInstruction(_instruction_);

        setListInst(_listInst_);

    }

    @Override
    public Object clone()
    {
        return new AInstructionListListInst(
            cloneNode(this._instruction_),
            cloneNode(this._listInst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstructionListListInst(this);
    }

    public PInstruction getInstruction()
    {
        return this._instruction_;
    }

    public void setInstruction(PInstruction node)
    {
        if(this._instruction_ != null)
        {
            this._instruction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instruction_ = node;
    }

    public PListInst getListInst()
    {
        return this._listInst_;
    }

    public void setListInst(PListInst node)
    {
        if(this._listInst_ != null)
        {
            this._listInst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listInst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instruction_)
            + toString(this._listInst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instruction_ == child)
        {
            this._instruction_ = null;
            return;
        }

        if(this._listInst_ == child)
        {
            this._listInst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instruction_ == oldChild)
        {
            setInstruction((PInstruction) newChild);
            return;
        }

        if(this._listInst_ == oldChild)
        {
            setListInst((PListInst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
