/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstSiInstruction extends PInstruction
{
    private PInstSi _instSi_;

    public AInstSiInstruction()
    {
        // Constructor
    }

    public AInstSiInstruction(
        @SuppressWarnings("hiding") PInstSi _instSi_)
    {
        // Constructor
        setInstSi(_instSi_);

    }

    @Override
    public Object clone()
    {
        return new AInstSiInstruction(
            cloneNode(this._instSi_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstSiInstruction(this);
    }

    public PInstSi getInstSi()
    {
        return this._instSi_;
    }

    public void setInstSi(PInstSi node)
    {
        if(this._instSi_ != null)
        {
            this._instSi_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instSi_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instSi_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instSi_ == child)
        {
            this._instSi_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instSi_ == oldChild)
        {
            setInstSi((PInstSi) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
