/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstAffectationInstruction extends PInstruction
{
    private PInstAffectation _instAffectation_;

    public AInstAffectationInstruction()
    {
        // Constructor
    }

    public AInstAffectationInstruction(
        @SuppressWarnings("hiding") PInstAffectation _instAffectation_)
    {
        // Constructor
        setInstAffectation(_instAffectation_);

    }

    @Override
    public Object clone()
    {
        return new AInstAffectationInstruction(
            cloneNode(this._instAffectation_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstAffectationInstruction(this);
    }

    public PInstAffectation getInstAffectation()
    {
        return this._instAffectation_;
    }

    public void setInstAffectation(PInstAffectation node)
    {
        if(this._instAffectation_ != null)
        {
            this._instAffectation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instAffectation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instAffectation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instAffectation_ == child)
        {
            this._instAffectation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instAffectation_ == oldChild)
        {
            setInstAffectation((PInstAffectation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
