/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AInstWriteInstruction extends PInstruction
{
    private PInstWrite _instWrite_;

    public AInstWriteInstruction()
    {
        // Constructor
    }

    public AInstWriteInstruction(
        @SuppressWarnings("hiding") PInstWrite _instWrite_)
    {
        // Constructor
        setInstWrite(_instWrite_);

    }

    @Override
    public Object clone()
    {
        return new AInstWriteInstruction(
            cloneNode(this._instWrite_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAInstWriteInstruction(this);
    }

    public PInstWrite getInstWrite()
    {
        return this._instWrite_;
    }

    public void setInstWrite(PInstWrite node)
    {
        if(this._instWrite_ != null)
        {
            this._instWrite_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._instWrite_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._instWrite_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._instWrite_ == child)
        {
            this._instWrite_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._instWrite_ == oldChild)
        {
            setInstWrite((PInstWrite) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
