/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AListDecVariable2ListDecVariable extends PListDecVariable
{
    private PDecVariable _decVariable_;
    private PListDecVariable2 _listDecVariable2_;

    public AListDecVariable2ListDecVariable()
    {
        // Constructor
    }

    public AListDecVariable2ListDecVariable(
        @SuppressWarnings("hiding") PDecVariable _decVariable_,
        @SuppressWarnings("hiding") PListDecVariable2 _listDecVariable2_)
    {
        // Constructor
        setDecVariable(_decVariable_);

        setListDecVariable2(_listDecVariable2_);

    }

    @Override
    public Object clone()
    {
        return new AListDecVariable2ListDecVariable(
            cloneNode(this._decVariable_),
            cloneNode(this._listDecVariable2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListDecVariable2ListDecVariable(this);
    }

    public PDecVariable getDecVariable()
    {
        return this._decVariable_;
    }

    public void setDecVariable(PDecVariable node)
    {
        if(this._decVariable_ != null)
        {
            this._decVariable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVariable_ = node;
    }

    public PListDecVariable2 getListDecVariable2()
    {
        return this._listDecVariable2_;
    }

    public void setListDecVariable2(PListDecVariable2 node)
    {
        if(this._listDecVariable2_ != null)
        {
            this._listDecVariable2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listDecVariable2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decVariable_)
            + toString(this._listDecVariable2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decVariable_ == child)
        {
            this._decVariable_ = null;
            return;
        }

        if(this._listDecVariable2_ == child)
        {
            this._listDecVariable2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decVariable_ == oldChild)
        {
            setDecVariable((PDecVariable) newChild);
            return;
        }

        if(this._listDecVariable2_ == oldChild)
        {
            setListDecVariable2((PListDecVariable2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
