/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicationExp4 extends PExp4
{
    private PExp4 _exp4_;
    private TMultiply _multiply_;
    private PExp5 _exp5_;

    public AMultiplicationExp4()
    {
        // Constructor
    }

    public AMultiplicationExp4(
        @SuppressWarnings("hiding") PExp4 _exp4_,
        @SuppressWarnings("hiding") TMultiply _multiply_,
        @SuppressWarnings("hiding") PExp5 _exp5_)
    {
        // Constructor
        setExp4(_exp4_);

        setMultiply(_multiply_);

        setExp5(_exp5_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicationExp4(
            cloneNode(this._exp4_),
            cloneNode(this._multiply_),
            cloneNode(this._exp5_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicationExp4(this);
    }

    public PExp4 getExp4()
    {
        return this._exp4_;
    }

    public void setExp4(PExp4 node)
    {
        if(this._exp4_ != null)
        {
            this._exp4_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp4_ = node;
    }

    public TMultiply getMultiply()
    {
        return this._multiply_;
    }

    public void setMultiply(TMultiply node)
    {
        if(this._multiply_ != null)
        {
            this._multiply_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiply_ = node;
    }

    public PExp5 getExp5()
    {
        return this._exp5_;
    }

    public void setExp5(PExp5 node)
    {
        if(this._exp5_ != null)
        {
            this._exp5_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp5_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp4_)
            + toString(this._multiply_)
            + toString(this._exp5_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp4_ == child)
        {
            this._exp4_ = null;
            return;
        }

        if(this._multiply_ == child)
        {
            this._multiply_ = null;
            return;
        }

        if(this._exp5_ == child)
        {
            this._exp5_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp4_ == oldChild)
        {
            setExp4((PExp4) newChild);
            return;
        }

        if(this._multiply_ == oldChild)
        {
            setMultiply((TMultiply) newChild);
            return;
        }

        if(this._exp5_ == oldChild)
        {
            setExp5((PExp5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
