/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class AReturnInstReturn extends PInstReturn
{
    private TRetour _retour_;
    private PExp _exp_;
    private TPointVir _pointVir_;

    public AReturnInstReturn()
    {
        // Constructor
    }

    public AReturnInstReturn(
        @SuppressWarnings("hiding") TRetour _retour_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TPointVir _pointVir_)
    {
        // Constructor
        setRetour(_retour_);

        setExp(_exp_);

        setPointVir(_pointVir_);

    }

    @Override
    public Object clone()
    {
        return new AReturnInstReturn(
            cloneNode(this._retour_),
            cloneNode(this._exp_),
            cloneNode(this._pointVir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReturnInstReturn(this);
    }

    public TRetour getRetour()
    {
        return this._retour_;
    }

    public void setRetour(TRetour node)
    {
        if(this._retour_ != null)
        {
            this._retour_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retour_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TPointVir getPointVir()
    {
        return this._pointVir_;
    }

    public void setPointVir(TPointVir node)
    {
        if(this._pointVir_ != null)
        {
            this._pointVir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pointVir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._retour_)
            + toString(this._exp_)
            + toString(this._pointVir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._retour_ == child)
        {
            this._retour_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._pointVir_ == child)
        {
            this._pointVir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._retour_ == oldChild)
        {
            setRetour((TRetour) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._pointVir_ == oldChild)
        {
            setPointVir((TPointVir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
