/* This file was generated by SableCC (http://www.sablecc.org/). */

package sc.node;

import sc.analysis.*;

@SuppressWarnings("nls")
public final class ATableauExp6 extends PExp6
{
    private PTableau _tableau_;

    public ATableauExp6()
    {
        // Constructor
    }

    public ATableauExp6(
        @SuppressWarnings("hiding") PTableau _tableau_)
    {
        // Constructor
        setTableau(_tableau_);

    }

    @Override
    public Object clone()
    {
        return new ATableauExp6(
            cloneNode(this._tableau_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATableauExp6(this);
    }

    public PTableau getTableau()
    {
        return this._tableau_;
    }

    public void setTableau(PTableau node)
    {
        if(this._tableau_ != null)
        {
            this._tableau_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tableau_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tableau_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tableau_ == child)
        {
            this._tableau_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tableau_ == oldChild)
        {
            setTableau((PTableau) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
